# Generated by Django 3.0.8 on 2020-09-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20200906_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='../static/news_feed_images/')),
                ('newsfeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.NewsFeed')),
            ],
        ),
    ]
