# Generated by Django 3.0.8 on 2020-09-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_newsfeedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsfeedimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='../images/news_feed_images/'),
        ),
        migrations.AlterField(
            model_name='newsfeedimage',
            name='newsfeed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.NewsFeed'),
        ),
    ]
