# Generated by Django 3.0.8 on 2020-08-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='poster_image',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
